image: python:2.7

cache:
  paths:
    - dist

build:
  stage: build
  script:
    - python setup.py sdist

test:
  stage: test
  script:
    - python setup.py test

cov:
  stage: test
  script:
    - ./cov.sh

deploy:
  stage: deploy
  script:
    - echo "Releasing dist"
    - pip install awscli
    - aws s3 cp dist/ s3://qerida/py-lib/ --recursive --exclude "*" --include "*.tar.gz"
  artifacts:
    paths:
      - dist/*.tar.gz
