image: python:2.7

build:
  stage: test
  script:
    # simple check if build is working
    - python setup.py sdist

test:
  stage: test
  script:
    - python setup.py test

cov:
  stage: test
  script:
    - ./cov.sh

